// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwgjltevhclquqgkdsfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Z2psdGV2aGNscXVxZ2tkc2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjQxMzgsImV4cCI6MjA3MzU0MDEzOH0.Wr1w0autkqAuEerR8yXVZQOIVkaz7Via5NYe5DT1Wlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});